export const SET_COURSES = 'SET_COURSES';
export const COURSES_LOADING = 'COURSES_LOADING';
export const COURSES_LOADING_FAILED = 'COURSES_LOADING_FAILED';
export const DELETE_COURSE = 'DELETE_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
